import { ReactNode } from 'react';
import {Montserrat} from "next/font/google";
import type {Metadata} from "next";

interface ErrorProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "WieldVPN",
    description: "Generated by create next app",
    icons: [
        {
            rel: 'apple-touch-icon',
            sizes: '180x180',
            url: '/apple-touch-icon.png',
        },
        {
            rel: 'icon',
            type: 'image/png',
            sizes: '32x32',
            url: '/favicon-32x32.png',
        },
        {
            rel: 'icon',
            type: 'image/png',
            sizes: '16x16',
            url: '/favicon-16x16.png',
        },
        {
            rel: 'shortcut icon',
            url: '/favicon.ico',
        },
    ],
    manifest: '/site.webmanifest',
}

const montserrat = Montserrat({
    weight: ['400', '600', '700'],
    subsets: ['latin']
})

export default function GlobalError({ children }: ErrorProps) {
    return (
        <html style={{background: 'black'}}>
        <link rel="icon" href="/app/favicon.ico" sizes="any"/>
        <body className={montserrat.className}>
        {children}
        </body>
        </html>
    );
}