import { ReactNode } from 'react';
import {Montserrat} from "next/font/google";
import type {Metadata} from "next";
import Head from "next/head";

interface ErrorProps {
    children: ReactNode;
}

export const metadata: Metadata = {
    title: "WieldVPN",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon/favicon.ico',
    }
}

const montserrat = Montserrat({
    weight: ['400', '600', '700'],
    subsets: ['latin']
})

export default function GlobalError({ children }: ErrorProps) {

    return (
        <html style={{background: 'black'}}>
        <body className={montserrat.className}>
        {children}
        </body>
        </html>
    );
}