import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "../globals.css";
import React, {ReactNode} from "react";
import {getMessages} from "next-intl/server";
import {NextIntlClientProvider} from "next-intl";
import {headers} from "next/headers";       // needed import
import {notFound} from "next/navigation";
import Head from "next/head";


const montserrat = Montserrat({
    weight: ['400', '600', '700'],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: "WieldVPN",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon/favicon.ico',
    }

}

type Props = {
    children: ReactNode,
    params: { locale: string }
}


export default async function RootLayout({children, params: {locale}}: Props) {
    const messages = await getMessages()
    const header = headers();
    const localeHeader = header.get('x-next-intl-locale');
    if (localeHeader === null) {
        notFound();
    }

    return (
        <html lang={locale}>
        <body className={montserrat.className}>
        <main className="min-h-screen">
            <NextIntlClientProvider messages={messages}>
                {children}
            </NextIntlClientProvider>
        </main>
        </body>
        </html>
    );
}
